description: Load 7.x NCCH crypto key

patches:
    patch1.bin:
        type: Memory
        subtype: NATIVE_FIRM
        options:
            - keyx
        variables:
            - setkey
            - unk
        versions:
            o3ds:
                0x56:
                    - 0x08056558
                    - 0x0805EA5C
                0x52:
                    - 0x08056558
                    - 0x0805EA5C
                0x50:
                    - 0x08056574
                    - 0x0805EA48
                0x49:
                    - 0x080575B4
                    - 0x0805FB48
                0x38:
                    - 0x080573EC
                    - 0x0805F994
                0x37:
                    - 0x08057434
                    - 0x0805FA00
                0x30:
                    - 0x0805728C
                    - 0x0805F800

    patch2.bin:
        type: NATIVE_FIRM
        memory:
            patch: patch1.bin
            variable: mem
        versions:
            o3ds:
                0x56: 0x080282F8
                0x52: 0x080282F8
                0x50: 0x080282F8
                0x49: 0x080282F8
                0x38: 0x080282F8
                0x37: 0x080282F8
                0x30: 0x080282F8
